# Generated by Django 5.2.10 on 2026-06-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_address_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(db_index=True, default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_identifier',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
