# Generated by Django 5.2.10 on 2026-06-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier_name',
            field=models.CharField(blank=True, default='DHL Express', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_status',
            field=models.CharField(db_index=True, default='Placed', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
