# Generated by Django 5.2.10 on 2026-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_backfill_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deletion_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_deletion', 'Pending Deletion'), ('archived', 'Archived')], db_index=True, default='active', max_length=20),
        ),
    ]
