# Generated by Django 5.2.10 on 2026-06-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rolechangelog'),
        ('api', '0021_product_image_file'),
    ]

    operations = [
    ]
