# Generated by Django 5.2.10

from django.db import migrations, models
from django.apps import apps as global_apps

def add_image_file_if_missing(apps, schema_editor):
    connection = schema_editor.connection
    table_name = 'api_product'
    column_name = 'image_file'
    
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute(
                f"SELECT 1 FROM information_schema.columns WHERE table_name='{table_name}' AND column_name='{column_name}'"
            )
            exists = cursor.fetchone()
        else: # sqlite
            cursor.execute(f"PRAGMA table_info({table_name})")
            exists = any(row[1] == column_name for row in cursor.fetchall())
            
        if not exists:
            Product_historical = apps.get_model('api', 'Product')
            Product_live = global_apps.get_model('api', 'Product')
            field = Product_live._meta.get_field(column_name)
            schema_editor.add_field(Product_historical, field)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_product_deletion_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='product',
                    name='image_file',
                    field=models.ImageField(blank=True, null=True, upload_to='products/'),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_image_file_if_missing),
            ],
        )
    ]
