# Generated by Django 5.2.10 on 2026-06-24 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_0020_rolechangelog_0021_product_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to='api.product'),
        ),
    ]
