# Generated by Django 5.2.10 on 2026-06-25 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_product_product_stock_non_negative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolechangelog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_changes_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolechangelog',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_change_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
