# Generated by Django 5.2.10 on 2026-06-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_rolechangelog_changed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Optional for phone-only signups; required for email signup.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signup_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='phone', help_text='Tracks which signup path created this account — informs which profile fields to expect/require.', max_length=10),
        ),
    ]
